# Generated by Django 5.2.12 on 2026-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('point', models.IntegerField(default=1)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
