# Generated by Django 5.2.15 on 2026-06-20 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='เลขที่แจ้งเหตุ')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อ')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('location', models.CharField(max_length=255, verbose_name='สถานที่')),
                ('reporter_name', models.CharField(max_length=150, verbose_name='ผู้แจ้ง')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('category', models.CharField(choices=[('electric', 'ไฟฟ้า'), ('water', 'ประปา'), ('road', 'ถนน'), ('security', 'ความปลอดภัย'), ('clean', 'ความสะอาด'), ('other', 'อื่น ๆ')], default='other', max_length=30, verbose_name='ประเภท')),
                ('priority', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง'), ('urgent', 'เร่งด่วน')], default='medium', max_length=20, verbose_name='ความเร่งด่วน')),
                ('status', models.CharField(choices=[('new', 'แจ้งใหม่'), ('received', 'รับเรื่องแล้ว'), ('progress', 'กำลังดำเนินการ'), ('completed', 'แก้ไขเสร็จ'), ('closed', 'ปิดงาน')], default='new', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แจ้ง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ปิดงาน')),
            ],
            options={
                'verbose_name': 'แจ้งเหตุ',
                'verbose_name_plural': 'รายการแจ้งเหตุ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'แจ้งใหม่'), ('received', 'รับเรื่องแล้ว'), ('progress', 'กำลังดำเนินการ'), ('completed', 'แก้ไขเสร็จ'), ('closed', 'ปิดงาน')], max_length=20, verbose_name='สถานะ')),
                ('note', models.TextField(verbose_name='บันทึกการดำเนินงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่บันทึก')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='myapp.incident', verbose_name='รายการแจ้งเหตุ')),
            ],
            options={
                'verbose_name': 'ติดตามผล',
                'verbose_name_plural': 'ประวัติการติดตามผล',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
