# Generated by Django 5.2.15 on 2026-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพสินค้า')),
                ('others', models.TextField(blank=True, null=True, verbose_name='ข้อมูลอื่น ๆ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
            ],
        ),
    ]
