# Generated by Django 5.2.15 on 2026-06-20 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_product_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='รูปประจำตัว'),
        ),
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='ประวัติส่วนตัว'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='เว็บไซต์ส่วนตัว'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='member',
            name='homenum',
            field=models.CharField(max_length=6, verbose_name='บ้านเลขที่'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='เบอร์โทร'),
        ),
        migrations.AlterField(
            model_name='member',
            name='point',
            field=models.IntegerField(default=1, verbose_name='คะแนน'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='รูปประจำตัว')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='ประวัติส่วนตัว')),
                ('website', models.URLField(blank=True, null=True, verbose_name='เว็บไซต์ส่วนตัว')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
